### ISSUE TITLE
Cinder: Mounting volumes in containers doesn't work when the volume isn't attached to the VM

### ISSUE THREAD

**Issue by agxs** [codedellemc/rexray#915]
# Summary

I'm trying to use the `rexray/cinder` docker plugin to mount cinder volumes inside containers. So far I've been unable to get this to work unless the cinder volume has been mounted on the VM.

My test docker command is:

```
docker run --rm -it --volume-driver=rexray/cinder  -v test-vol-1:/data busybox sh
```

I've already created by volume using OpenStack.

Running the above command gives the following error:

```
docker: Error response from daemon: error while mounting volume '/var/lib/docker/plugins/98f0aacacd60baa40de8e5aa3fc51cf29ec8d0fae7c5e01812b1e00fcb34e041/rootfs': VolumeDriver.Mount: {"Error":"problem with device discovery"}.
```

However, this command does successfully mount the cinder volume on the VM, just not inside the container. And then running the above command a *second* time works.

If I manually attach the cinder volume to the VM, then the above command works first time. It only seems to fail when the cinder volume *isn't* attached to the VM.

## Version

```
$ docker plugin ls
ID                  NAME                   DESCRIPTION                           ENABLED
98f0aacacd60        rexray/cinder:latest   REX-Ray for Cinder Persistent Disks   true
```

I believe `latest` points to 0.9.2 at the moment.

```
$ docker plugin inspect rexray/cinder
[
    {
        "Config": {
            "Args": {
                "Description": "",
                "Name": "",
                "Settable": null,
                "Value": null
            },
            "Description": "REX-Ray for Cinder Persistent Disks",
            "Documentation": "https://github.com/codedellemc/rexray/.docker/plugin/cinder",
            "Entrypoint": [
                "/rexray.sh",
                "rexray",
                "start",
                "-f",
                "--nopid"
            ],
            "Env": [
                {
                    "Description": "",
                    "Name": "REXRAY_FSTYPE",
                    "Settable": [
                        "value"
                    ],
                    "Value": "ext4"
                },
                {
                    "Description": "",
                    "Name": "REXRAY_LOGLEVEL",
                    "Settable": [
                        "value"
                    ],
                    "Value": "warn"
                },
                {
                    "Description": "",
                    "Name": "REXRAY_PREEMPT",
                    "Settable": [
                        "value"
                    ],
                    "Value": "false"
                },
                {
                    "Description": "",
                    "Name": "CINDER_AUTHURL",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_USERNAMEID",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_USERNAME",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_PASSWORD",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_TOKENID",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_TENANTID",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_TENANTNAME",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_DOMAINID",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                },
                {
                    "Description": "",
                    "Name": "CINDER_DOMAINNAME",
                    "Settable": [
                        "value"
                    ],
                    "Value": ""
                }
            ],
            "Interface": {
                "Socket": "rexray.sock",
                "Types": [
                    "docker.volumedriver/1.0"
                ]
            },
            "Linux": {
                "AllowAllDevices": true,
                "Capabilities": [
                    "CAP_SYS_ADMIN"
                ],
                "Devices": null
            },
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/dev",
                    "Name": "",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": null,
                    "Source": "/dev",
                    "Type": "bind"
                }
            ],
            "Network": {
                "Type": "host"
            },
            "PropagatedMount": "/var/lib/libstorage/volumes",
            "User": {},
            "WorkDir": "",
            "rootfs": {
                "diff_ids": [
                    "sha256:f6698d039538701f50279c34b67f1efa8c4530c0ca9ddbbf65b39858202f3cee"
                ],
                "type": "layers"
            }
        },
        "Enabled": true,
        "Id": "98f0aacacd60baa40de8e5aa3fc51cf29ec8d0fae7c5e01812b1e00fcb34e041",
        "Name": "rexray/cinder:latest",
        "PluginReference": "rexray/cinder:latest",
        "Settings": {
            "Args": [],
            "Devices": [],
            "Env": [
                "REXRAY_FSTYPE=ext4",
                "REXRAY_LOGLEVEL=debug",
                "REXRAY_PREEMPT=true",
                "CINDER_AUTHURL=https://keystone.****/v3",
                "CINDER_USERNAMEID=",
                "CINDER_USERNAME=****",
                "CINDER_PASSWORD=****",
                "CINDER_TOKENID=",
                "CINDER_TENANTID=****",
                "CINDER_TENANTNAME=",
                "CINDER_DOMAINID=",
                "CINDER_DOMAINNAME=****"
            ],
            "Mounts": [
                {
                    "Description": "",
                    "Destination": "/dev",
                    "Name": "",
                    "Options": [
                        "rbind"
                    ],
                    "Settable": null,
                    "Source": "/dev",
                    "Type": "bind"
                }
            ]
        }
    }
]
```

```
$ docker --version
Docker version 17.03.1-ce, build c6d412e
```

I"m running Docker on Ubuntu 16.04.

## Expected Behavior

The expected behavior is that the cinder volume is mounted on the container even if the volume isn't mounted on the VM before the `docker run` command is run.

## Actual Behavior

The `docker run` command above only works if it is run twice(first time to mount the cinder volume on the VM which exits with an error, second time to actually run the container). Or the `docker run` command will work first time if the cinder volume is already mounted on the VM using OpenStack's tools.

## Steps To Reproduce

1. Create an Ubuntu 16.04 VM in OpenStack
2. Install Docker using the instuctions at https://docs.docker.com/engine/installation/linux/docker-ce/ubuntu/#install-from-a-package
3. Install Rexray:
```
docker plugin install rexray/cinder \
CINDER_AUTHURL=https://keystone.****/v3 \
CINDER_USERNAME=**** \
CINDER_PASSWORD=**** \
CINDER_TENANTID=**** \
CINDER_DOMAINNAME=**** \
REXRAY_PREEMPT=true
```
4. `docker volume create -d rexray/cinder test-vol-1` - this creates a cinder volume but *doesn't* attach it to the current VM
5. `docker run --rm -it --volume-driver=rexray/cinder  -v test-vol-1:/data busybox sh`
6. Shows the above error about device discovery
7. Check OpenStack to see that the newly created volume is now attached to the VM
8. `docker run --rm -it --volume-driver=rexray/cinder  -v test-vol-1:/data busybox sh` now succeeds

## Logs

Since I'm using the docker plugin rather than the Rexray service the logs came from `journalctl`:

https://gist.github.com/agxs/1744c52d45e7e5ee57493d8f39484f5f

**Comment by codenrhoden** [comment]
@agxs This is something I would have to recreate in order to see what is going on.

When REX-Ray asks Cinder to attach a volume to a host, Cinder also tells us what device the volume should be present at (e.g. `/dev/sdb`). If we have an issue finding that volume at that device, that's when you see the error you are seeing...

I'll have to look into this. Thanks for the report!

**Comment by MatMaul** [comment]
This is perhaps related to some permissions issues/missing bindmount on /dev with the docker plugin packaging, this simple use case was working fine with rexray standard when merged.

**Comment by MatMaul** [comment]
Actually this commit seems to have break the driver:
https://github.com/codedellemc/libstorage/commit/d0e278a68e222eb200ab0270b67d0175d3be857b
@codenrhoden 
Previously just reporting a string of possible dev devices (without associated volume id) was enough, since the actual device is returned by VolumeAttach and then matches against LocalDevices right ? It changed ?

Actually in the case where VolumeAttach return a valid dev path I don't think we should call LocalDevices at all no ?

**Comment by giovannicandido** [comment]
Same issue using rexray as a service

**Comment by akutz** [comment]
Fixed by #935.

**Comment by agxs** [comment]
I can confirm the current version(0.10.2 I think) correctly mounts volumes with the above commands 👍

**Comment by olivibernard** [comment]
I run a similar test in 0.10.2 and I still get the error in swarm manager logs 
`Error response from daemon: error while mounting volume '/': VolumeDriver.Mount: {\"Error\":\"error detaching volume\"}"`

**Comment by MatMaul** [comment]
This is bug #913
